services:
  postgres:
    image: postgres:16-alpine
    container_name: pms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: pms_password
      POSTGRES_DB: parking_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
